graph LR
  http___dbpedia_org_resource_Proxima_Centauri_b("dbpedia.org/resource/Proxima_Centauri_b")
  click http___dbpedia_org_resource_Proxima_Centauri_b "http://dbpedia.org/resource/Proxima_Centauri_b"
  Literal_0ed26ad5b509[["{“eccentricity“:0.11,“equilibriumTemperature“:234,“orbitalPeriod“:11.186,“semiMajorAxis“:0.0485}"]]
  http___dbpedia_org_resource_Proxima_Centauri_b --- Edge_8070d2b95411(["schema.org/additionalProperty"])--> Literal_0ed26ad5b509
  click Edge_8070d2b95411 "https://schema.org/additionalProperty"
  classDef predicate fill:#1f2233,stroke:transparent,color:#f8fafc,stroke-width:0px;
  classDef hidden fill:transparent,stroke:transparent,color:transparent,stroke-width:0px;
  classDef nanopubdot fill:#0f172a,stroke:#0f172a,color:transparent,stroke-width:2px;
  classDef transparent fill:transparent,stroke:transparent,color:transparent,stroke-width:0px;
  
