# This workflow builds and publishes the extended profile note.
name: Build and Publish YAML-LD Extended Profile

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/extended-profile.yml'
      - 'common/**'
      - 'extended-profile/**'
      - 'package-lock.json'
      - 'package.json'
      - 'w3c.json'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/extended-profile.yml'
      - 'common/**'
      - 'extended-profile/**'
      - 'package-lock.json'
      - 'package.json'
      - 'w3c.json'

jobs:
  tests:
    name: Build, Validate and Deploy Extended Profile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Validate via ReSpec
    # See https://github.com/w3c/spec-prod/blob/main/docs/examples.md
    - name: ReSpec Checker
      uses: w3c/spec-prod@v2
      with:
        TOOLCHAIN: respec
        SOURCE: extended-profile/index.html
        # We would like to enable link validation here, but spec-prod's
        # link-checker path currently fails upstream:
        # https://github.com/w3c/spec-prod/issues/222
        # VALIDATE_LINKS: true
        VALIDATE_MARKUP: true
        W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
        W3C_WG_DECISION_URL: https://www.w3.org/2026/04/08-json-ld-minutes.html#e967
        W3C_BUILD_OVERRIDE: |
          specStatus: DNOTE
          shortName: yaml-ld-extended-profile
